# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 09:01
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=500)),
                ('service_description', models.CharField(max_length=500)),
                ('service_type', models.CharField(choices=[('CD', 'Custom Data'), ('RP', 'Report')], default='CD', max_length=2)),
                ('deadline', models.DateField(default=datetime.date(2017, 10, 8))),
                ('budget', models.IntegerField()),
                ('file', models.FileField(upload_to=b'')),
                ('category_type', models.CharField(choices=[('C1', 'Category 1'), ('C2', 'Category 2'), ('C3', 'Category 3')], default='C1', max_length=2)),
                ('provider', models.CharField(choices=[('NT', 'NTUA'), ('EX', 'EXHILE'), ('AL', 'Every BDO Provider')], default='NT', max_length=2)),
                ('email_notification', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
