# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2017, 10, 10)),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
