# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0002_auto_20171010_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2017, 10, 12)),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='keywords',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='service_description',
            field=models.TextField(max_length=500),
        ),
    ]
