# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 12:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userrequests', '0003_auto_20171012_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2017, 10, 18)),
        ),
        migrations.AddField(
            model_name='messages',
            name='requestid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userrequests.UserRequests'),
        ),
        migrations.AddField(
            model_name='messages',
            name='userpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replied_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='userreq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
