# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0004_auto_20171018_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2017, 10, 19)),
        ),
    ]
