# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 12:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userrequests', '0005_auto_20171019_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userrequests.Messages')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2017, 10, 20)),
        ),
    ]
