# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0006_auto_20171020_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagenotify',
            name='userid',
        ),
        migrations.AddField(
            model_name='messagenotify',
            name='user',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messages',
            name='userpost',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messages',
            name='userreq',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2017, 10, 24)),
        ),
        migrations.AlterField(
            model_name='userrequests',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
