# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-27 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrequests', '0007_auto_20171024_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequests',
            name='deadline',
            field=models.DateField(default=datetime.date(2017, 11, 27)),
        ),
    ]
